services:
  web:
    image: php/server:1
    env_file:
      - .env
    environment:
      DOCKER: true
      BOLUK: false
    volumes:
      - ./web:/var/www/html/public/
      - ./add.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 80:8080
    networks:
      e-network:
  database:
    image: mysql:8.1.0
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    networks:
      e-network:
        aliases:
          - database
networks:
  e-network: